all:
	cd 00-maxServer; make
	cd 01-contaChar; make
	cd 02-findStr; make
	cd 03-buttafuori; make
	cd 04-udp; make
	cd 05-multiplexing; make
	cd 06-chat; make
	cd 07-tris; make
	cd 08-battagliaNavale; make
	cd 10-GestoreAsteOnline; make
	
clean:
	cd 00-maxServer; make clean
	cd 01-contaChar; make clean
	cd 02-findStr; make clean
	cd 03-buttafuori; make clean
	cd 04-udp; make clean
	cd 05-multiplexing; make clean
	cd 06-chat; make clean
	cd 07-tris; make clean
	cd 08-battagliaNavale; make clean
	cd 10-GestoreAsteOnline; make clean
	