#define NEW_SERVER_STRING "new server-"
#define NEW_CLIENT_STRING "new client"
#define CLIENT_LOGIN_REGISTRATION "login_registration-"
#define CLIENT_LOGIN "login-"
#define NEW_CLIENT_REGISTRATION "registration-"
#define NEW_CLIENT_REGISTRATION_ERROR "The passwords inserted aren't the same\nWhat would you want to do:\n1 - Login\n2 - Register as a new user\n\n"
#define NEW_CLIENT_REGISTRATION_ERROR_PRESENT "Username already exists\nWhat would you want to do:\n1 - Login\n2 - Register as a new user\n\n"
#define NEW_CLIENT_REGISTRATION_PASSWORD "Please insert the password you want to use now please\n"
#define NEW_CLIENT_REGISTRATION_PASSWORD_REPEAT "Please confirm the password, inserting it again please\n"
#define NEW_CLIENT_REGISTRATION_COMPLETE "Thank you for registering. You can now login with your credential\n\nWhat would you want to do:\n1 - Login\n2 - Register as a new user\n\n"
#define CLIENT_USERNAME "username-"
#define CLIENT_PASSWORD "password-"
#define RELOGGING "client trying to login again"
#define RELOGGED "relogged:"
#define NO_MORE_SERVERS "There's no other server to connect to. Please wait, the client will try again to connect to a new server\n"
#define CLIENT_PASSWORD_CONFIRM "password_confirm-"
#define WELCOME_CLIENT "Welcome to ebay-clone! What would you want to do:\n1 - Login\n2 - Register as a new user\n\n"
#define WELCOME_CLIENT_USERNAME "Please insert your username\n"
#define WELCOME_CLIENT_PASSWORD "Please insert your password now\n"
#define CLIENT_REGISTRATION_USERNAME "Please insert the username you would like to use\n"
#define WELCOME_CLIENT_WRONG_LOGIN "Username or password you inserted are wrong\nWhat would you want to do:\n1 - Login\n2 - Register as a new user\n\n"
#define WELCOME_CLIENT_LOGGED "Thanks, you are now logged in. You can now connect to the server:"
#define NO_SERVERS "No servers connected at the moment. Please wait, the client will try again to connect to a new server\n"
#define ADD_SERVER_STRING_OK "New server added successfully\n"
#define ADD_SERVER_STRING_ERROR "There was an error adding the new server\n"
#define UNKNOWN_MESSAGE "Unknown message, please re-enter what you needed\n"
#define UNKNOWN_MESSAGE_LOGIN_REGISTRATION "Unknown message\n\nWelcome to ebay-clone! What would you want to do:\n1 - Login\n2 - Register as a new user\n\n"

#define MENU "Welcome to your menu\n\n1 - Show latest items on sale\n2 - Search item by name\n3 - Bids\n4 - Items won\n5 - Items on sale\n6 - Items sold\n7 - Sell an item\n\n0 - Logout and exit\n\n\nPlease select what you want to do:\n"
#define SELECT_MENU "Menu voice-"
#define UNKNOWN_MENU "Unknown menu selection, please retry\n"
#define SEARCH_MENU "Insert the id of the item you want to bid or 0 to go back to main menu\n"
#define GOODBYE "Thanks for whatever you have done here! Hope to see you again soon enought!\n"
#define GOODBYE_OK "Ok you can close the connection\n"
#define NO_RESULTS "No results found for your search sorry\n\n"
#define CLIENT_GOODBYE "closing connection-"
#define SEARCH_SELECT "search selection-"
#define SEARCH_BY_NAME "Please insert the name of the item you'd like to look for\n"
#define SEARCH_BY_NAME_CLIENT "search by name-"
#define SHOW_LATEST_ITEMS "SELECT * FROM items WHERE start_date < NOW() AND end_date > NOW() ORDER BY end_date LIMIT 10"
#define SELL_ITEM "Tell us the name of the item you'd like to sell please. The bid will start from 1 credit and it'll last 3 days from now!\n"
#define SELL_ITEM_RESPONSE "selling item-"

#define ITEM_ON_SALE "\n\nThe item you requested to sell is on sale now\n\n"
#define BID "How much would you bid on this item?"
#define BID_ITEM "bid item-"

#define NAME_ROW 1
#define SELLER_ID_ROW 4
#define ACTUAL_PRICE_ROW 5
#define ACTUAL_WINNING_USER_ROW 6
